### ISSUE TITLE
Possible typo in chart-values.yaml

### ISSUE THREAD

**Issue by ceddlyburge** [benc-uk/dapr-store#20]
Hi There

I have been following this repo, the blog post by Carlos, and various other resources to attempt to get a kubernetes ingress controller working with Dapr.

I spent some time trying to get things working, and I think the problem is with this line, which should be `app-id`, instead of just `id`.

https://github.com/benc-uk/dapr-store/blob/eeb108fdeefb459655d0bf72b1040d49093b4e66/deploy/ingress/chart-values.yaml#L9

This same typo appears on Carlos' original blog post.

I think it also needs to match the name from the `helm install` command, which is probably worth documenting.

Cheers, Cedd

**Comment by benc-uk** [comment]
It's likely that this was changed since Dapr went to v1

This project hasn't been tested with v2 yet, it's on my very long todo list to take a look at

Good catch thanks

**Comment by benc-uk** [comment]
I've been updating the app to work with Dapr 1.1 so this is fixed now
